default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5

development:
  <<: *default
  database: rails5_dev
  username: root
  password:

test:
  <<: *default
  database: rails5_test
  host: <%= ENV['TEST_MYSQL_HOST'] || 'localhost' %>
  username: <%= ENV['TEST_MYSQL_USER'] || 'root' %>
  password: <%= ENV['TEST_MYSQL_PASSWORD'] %>

production:
  <<: *default
  database: <%= ENV['PRODUCTION_MYSQL_DB'] %>
  host: <%= ENV['PRODUCTION_MYSQL_HOST'] %>
  username: <%= ENV['PRODUCTION_MYSQL_USER'] %>
  password: <%= ENV['PRODUCTION_MYSQL_PASSWORD'] %>

