default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  port: 3306

development:
  <<: *default
  database: rails5_dev
  username: root
  password:

test:
  <<: *default
  database: rails5_test
  host:     <%= ENV['TEST_MYSQL_HOST'] || 'localhost' %>
  username: <%= ENV['TEST_MYSQL_USER'] || 'root' %>
  password: <%= ENV['TEST_MYSQL_PASSWORD'] || '' %>
  socket: /tmp/mysql.sock

production:
  <<: *default
  database: <%= ENV['PRODUCTION_MYSQL_DB'] %>
  host:     <%= ENV['PRODUCTION_MYSQL_HOST'] %>
  username: <%= ENV['PRODUCTION_MYSQL_USER'] %>
  password: <%= ENV['PRODUCTION_MYSQL_PASSWORD'] %>

