# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e5a3b02cf6e6ad96bf5dde0f22dd287adb11c192ef08dcf84857bcde10c324a77510e786f20b52b6279ab20510c34525301674fb62a164fa7bc1985240d7f11b

test:
  secret_key_base: 2d2d40b0e35e596ff87d322a52ba96bd898fed550f7c521d13db90e55c75b3fcafe1a43558b0e8dda13d3d011897b05a3dca32391a7376a2fc9773586df8723e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
